import com.google.android.material.color.utilities.*;
import java.io.*;
import java.lang.reflect.Method;
import java.util.*;

/** Generates complete M3 day/night palettes with Material's own colour and contrast utilities. */
public class Gen {
    public static void main(String[] a) throws Exception {
        String res = a[0];
        String[] roles = a[1].split(",");
        String[][] presets = {
            // Teal keeps the app's hue; indigo is a deep blue.
            // Normalize these two accents before Fidelity so the large connection button
            // has a moderate tone and chroma, with coordinated secondary colours.
            {"teal", "006874", "soft-fidelity"},
            {"coral", "CF5B42", "fidelity"}, // shrimp.fish/brand.css
            {"indigo", "0041FF", "soft-fidelity"},
            {"monochrome", "000000", "monochrome"},
            {"red", "E57373", "tonal"}, {"orange", "FF8A3D", "tonal"},
            {"yellow", "D9A400", "tonal"}, {"green", "4CAF50", "tonal"},
            {"forest", "1B4332", "fidelity"}, {"cyan", "29B6F6", "tonal"},
            {"blue", "4285F4", "tonal"}, {"navy", "0F2854", "fidelity"},
            {"purple", "7C4DFF", "tonal"}, {"lavender", "B39DDB", "tonal"},
            {"pink", "D81B60", "tonal"}, {"brown", "795548", "fidelity"},
        };
        MaterialDynamicColors mdc = new MaterialDynamicColors();
        for (boolean dark : new boolean[]{false, true}) {
            StringBuilder sb = new StringBuilder("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<!-- Generated by scripts/themegen via Material's color utilities. Do not edit by hand. -->\n<resources>\n");
            for (String[] p : presets) {
                Hct seed = Hct.fromInt(0xFF000000 | Integer.parseInt(p[1], 16));
                if (p[2].equals("soft-fidelity")) {
                    // Tone 60 matches the coral container's perceived brightness. A chroma
                    // ceiling of 40 avoids neon blue without washing out the teal accent.
                    seed = Hct.from(seed.getHue(), Math.min(seed.getChroma(), 40.0), 60.0);
                }
                DynamicScheme s = switch (p[2]) {
                    case "fidelity", "soft-fidelity" -> new SchemeFidelity(seed, dark, 0.0);
                    case "monochrome" -> new SchemeMonochrome(seed, dark, 0.0);
                    default -> new SchemeTonalSpot(seed, dark, 0.0);
                };
                sb.append(String.format("    <color name=\"preset_%s_seed\">#%08X</color>\n", p[0], seed.toInt()));
                Map<String, Integer> colors = new HashMap<>();
                for (String r : roles) {
                    Method mm = MaterialDynamicColors.class.getMethod(r);
                    int argb = ((DynamicColor) mm.invoke(mdc)).getArgb(s);
                    colors.put(r, argb);
                    sb.append(String.format("    <color name=\"preset_%s_%s\">#%08X</color>\n", p[0], r, argb));
                }
                validate(p[0], colors);
            }
            sb.append("</resources>\n");
            String dir = res + (dark ? "/values-night" : "/values");
            try (Writer w = new FileWriter(dir + "/colors_theme_presets.xml")) { w.write(sb.toString()); }
        }
    }

    /** Catch unreadable foreground/container pairs before resources reach the app. */
    private static void validate(String preset, Map<String, Integer> colors) {
        String[][] pairs = {
            {"primary", "onPrimary"}, {"primaryContainer", "onPrimaryContainer"},
            {"secondary", "onSecondary"}, {"secondaryContainer", "onSecondaryContainer"},
            {"tertiary", "onTertiary"}, {"tertiaryContainer", "onTertiaryContainer"},
            {"surface", "onSurface"}, {"surfaceVariant", "onSurfaceVariant"},
            {"error", "onError"}, {"errorContainer", "onErrorContainer"},
        };
        for (String[] pair : pairs) {
            double ratio = Contrast.ratioOfTones(Hct.fromInt(colors.get(pair[0])).getTone(),
                Hct.fromInt(colors.get(pair[1])).getTone());
            if (ratio < 4.5) throw new IllegalStateException(preset + ": contrast below 4.5 for " + pair[0]);
        }
        if (preset.equals("monochrome")) {
            for (Map.Entry<String, Integer> c : colors.entrySet()) {
                if (c.getKey().toLowerCase(Locale.ROOT).contains("error")) continue;
                int rgb = c.getValue();
                if (((rgb >> 16) & 255) != ((rgb >> 8) & 255) || ((rgb >> 8) & 255) != (rgb & 255)) {
                    throw new IllegalStateException("Tinted monochrome role: " + c.getKey());
                }
            }
        }
    }
}
